stages:
  - test
  - production
  
  
services:
  - postgres:latest

variables:
  POSTGRES_DB: votepolicy
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

test:
    script:
    - export DATABASE_URL=postgres://postgres:@localhost:5432/votepolicy
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test

Production:
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
