# Generated by Django 3.1.5 on 2021-03-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20210326_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vote.policy'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vote.vote'),
        ),
        migrations.AlterField(
            model_name='japat',
            name='Category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vote.category'),
        ),
        migrations.AlterField(
            model_name='japat',
            name='statusJapat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vote.statusjapat'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='spotify',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
