# Generated by Django 3.1.5 on 2021-03-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20210326_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japat',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='japat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
