# Generated by Django 3.1.5 on 2021-03-26 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20210326_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusvote',
            name='vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='statusVote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='vote.statusvote'),
        ),
    ]
