# Generated by Django 3.1.5 on 2021-05-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20210531_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='japat',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
