# Generated by Django 3.1.5 on 2021-05-31 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_japat_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vote.category'),
        ),
        migrations.AlterField(
            model_name='japat',
            name='statusJapat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vote.statusjapat'),
        ),
    ]
