# Generated by Django 3.1.5 on 2021-05-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20210531_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
