# Generated by Django 3.1.5 on 2021-05-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_auto_20210531_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japat',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
