# Generated by Django 3.1.5 on 2021-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_auto_20210531_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='japat',
            name='voters',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
