# Generated by Django 3.1.5 on 2021-08-13 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_japat_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vote.category'),
        ),
    ]
