# Generated by Django 3.1.5 on 2021-08-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_auto_20210813_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
