# Generated by Django 3.1.5 on 2021-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_auto_20210823_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='category',
        ),
        migrations.AddField(
            model_name='policy',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='vote.Category'),
        ),
    ]
