# Generated by Django 3.1.5 on 2021-08-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0017_vote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='statusVote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='vote.statusvote'),
        ),
    ]
