# Generated by Django 3.1.5 on 2021-08-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0021_comment_japat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='japat',
        ),
    ]
