# Generated by Django 3.1.7 on 2021-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0023_comment_japat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='japat',
            name='file1',
        ),
        migrations.AddField(
            model_name='japat',
            name='url_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
