# Generated by Django 3.1.7 on 2021-09-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0024_auto_20210909_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='category',
        ),
        migrations.AddField(
            model_name='policy',
            name='category',
            field=models.ManyToManyField(blank=True, to='vote.Category'),
        ),
    ]
