# Generated by Django 3.1.7 on 2021-11-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0025_auto_20210926_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
