# Generated by Django 3.1.7 on 2021-11-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0026_comment_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='overview',
        ),
        migrations.AddField(
            model_name='japat',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
