# Generated by Django 3.1.7 on 2021-12-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0027_auto_20211120_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japat',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
