"""
Django settings for vp project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import dotenv_values
from firebase import Firebase

configFirebase = {
    "apiKey": "AIzaSyCelehjfDyadXpkokZWNIwBuDr3eopE-SE",
    "authDomain": "votepolicy-4d7d4.firebaseapp.com",
    "projectId": "votepolicy-4d7d4",
    "databaseURL": "https://lvotepolicy-4d7d4-default-rtdb.firebaseio.com/",
    "storageBucket": "votepolicy-4d7d4.appspot.com",
    "messagingSenderId": "971109116089",
    "appId": "1:971109116089:web:749c07ed94b967e1c35368",
    "measurementId": "G-S04PLJQMKV",
}


firebase = Firebase(configFirebase)
storage = firebase.storage()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

config = dotenv_values(".env")

SECRET_KEY = config['SECRET_KEY']
RECAPTCHA_SITE_KEY = os.getenv('RECAPTCHA_SITE_KEY') or config['RECAPTCHA_SITE_KEY']
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY') or config['RECAPTCHA_SECRET_KEY']


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^p#k*)5w5=0*7c4a@u9c+h9jwe0a&kkrj7_4in-bp0$*p+zzw%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vote',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DB_PASS = config['POSTGRES_PASS'] == None
DB_PASSWORD = ''
if DB_PASS:
    DB_PASSWORD = os.getenv('POSTGRES_PASS')
else:
    DB_PASSWORD = config['POSTGRES_PASS']

DB_PASS = config['POSTGRES_PASS'] == None
DB_PASSWORD = ''
if DB_PASS:
    DB_PASSWORD = os.getenv('POSTGRES_PASS')
else:
    DB_PASSWORD = config['POSTGRES_PASS']


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'votepolicy',
        'USER': 'postgres',
        'PASSWORD': DB_PASSWORD,
        'HOST': 'localhost',
        'PORT': '5432'
    }
}

DB_URL = os.getenv('DATABASE_URL') != None
if DB_URL:
    DATABASES['default'] = dj_database_url.config()




# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
   
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
